<?php
// auto-generated page manifest — do not edit by hand
return [
  "en" => [
    "index" => ['title' => "Middle East University — Learn. Belong. Lead. — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => false],
    "sitemap" => ['title' => "Site Map — Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/accessibility" => ['title' => "Students with Special Needs &amp; Accommodations — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/accreditation" => ['title' => "Accreditation — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/campus-library" => ['title' => "Library — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/campus" => ['title' => "Campus — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/civic-engagement" => ['title' => "Civic Engagement — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/contact" => ['title' => "Contact Us — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/core-values" => ['title' => "Core Values — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/facilities" => ['title' => "Campus &amp; Facilities — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/inquire" => ['title' => "Contact us — Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/library" => ['title' => "Library — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/meu-general-policy" => ['title' => "MEU General Policy — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/meu-in-numbers" => ['title' => "MEU in Numbers — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/meu-in-words" => ['title' => "About MEU — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/meu-map" => ['title' => "MEU Map — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/org-structure" => ['title' => "Organizational Structure — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/partnerships" => ['title' => "Partnerships &amp; Signed Agreements — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/quality-assurance" => ['title' => "Quality Assurance Policy — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/strategic-plan" => ['title' => "Strategic Plan &amp; Structure — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/university-objectives" => ['title' => "University Objectives — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/university-strategic-plan" => ['title' => "Strategic Plan 2019/2024 — Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/university-structure" => ['title' => "University Structure — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/university-terminology" => ['title' => "University Terminology — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/vision-mission" => ['title' => "Vision, Mission &amp; Objectives — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/visit" => ['title' => "Plan a Visit — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/why-meu" => ['title' => "Why MEU? — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "academics/ects" => ['title' => "ECTS — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-allied-medical" => ['title' => "Faculty of Allied Medical Sciences — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-architecture" => ['title' => "Faculty of Architecture & Design — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-arts" => ['title' => "Faculty of Arts & Sciences — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-business" => ['title' => "Faculty of Business — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-it" => ['title' => "Faculty of Information Technology — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-law" => ['title' => "Faculty of Law — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-media" => ['title' => "Faculty of Media — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-nursing" => ['title' => "Faculty of Nursing — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-pharmacy" => ['title' => "Faculty of Pharmacy — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/master-programs" => ['title' => "Master&#x27;s Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/pg-majors" => ['title' => "Faculties & Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/prog-ai" => ['title' => "BSc Artificial Intelligence — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/prog-cis" => ['title' => "BSc Computer Information Systems — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/prog-cloud" => ['title' => "MSc Cloud Computing Services &amp; Security — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/prog-cs" => ['title' => "BSc Computer Science — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/prog-cyber" => ['title' => "BSc Cyber Security — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/programs" => ['title' => "Explore our Programs — MEU", 'bodyClass' => "about-page programs-page", 'css' => true, 'spacer' => true],
    "academics/technical-college" => ['title' => "Faculty of Technical College — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/ug-majors" => ['title' => "Faculties & Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-engineering" => ['title' => "Engineering Services — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-financial" => ['title' => "Financial Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-health" => ['title' => "Health Care — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-hr" => ['title' => "Human Resources Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-it" => ['title' => "IT Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-legal" => ['title' => "Legal Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-media-pr" => ['title' => "Media & PR Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-presidency" => ['title' => "All Departments — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-procurement" => ['title' => "Procurement & Tendering — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-warehouses" => ['title' => "Warehouses Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/admission" => ['title' => "Admission and Registration — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/certify-foreign" => ['title' => "Certifying Foreign Certificates — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/epayment" => ['title' => "Electronic Payment Steps — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/fees" => ['title' => "Fees — Tuition & Insurance | MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/hd-fees" => ['title' => "Tuition Fees (Higher Diploma) — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/pg-fees" => ['title' => "Fees & Insurance — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/pg-procedures" => ['title' => "Procedures — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/pg-requirements" => ['title' => "Admission Requirements — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/scholarships-aid" => ['title' => "Scholarships & Financial Aid — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/talent-scholarship" => ['title' => "Talent Scholarship | MEU Admission", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/transfer-students" => ['title' => "Transfer Students — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/ug-documents" => ['title' => "Documents Required — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/ug-fees" => ['title' => "Fees & Insurance — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/ug-procedures" => ['title' => "Procedures — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/ug-requirements" => ['title' => "Admission Requirements — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-academic-development-achievements" => ['title' => "Achievements — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-academic-development-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-academic-development-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-academic-development-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-academic-development" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-accreditation-quality-achievements" => ['title' => "Achievements — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-accreditation-quality-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-accreditation-quality-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-accreditation-quality-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-accreditation-quality" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-consulting-training-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-consulting-training-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-consulting-training-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-consulting-training" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-heritage-revival-gallery" => ['title' => "Photo Gallery — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-heritage-revival-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-heritage-revival-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-heritage-revival-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-heritage-revival" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-hikmi-therapy" => ['title' => "Center for Therapeutic Therapy — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-house-of-art" => ['title' => "House of Art — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-innovation-entrepreneurship-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-innovation-entrepreneurship-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-innovation-entrepreneurship-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-innovation-entrepreneurship" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-media-training-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-media-training-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-media-training-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-media-training" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-recruitment" => ['title' => "Students Recruitment Center — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/centers-institutes" => ['title' => "Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/training-enterprise" => ['title' => "Training & Enterprise — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/board-of-directors" => ['title' => "Board of Trustees — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "governance/board-of-trustees" => ['title' => "Board of Trustees — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/chairman-trustees" => ['title' => "Chairman of the Board of Trustees — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/control-audit" => ['title' => "Control & Internal Audit Unit — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/council-graduate-studies" => ['title' => "Council of Graduate Studies — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/council-of-deans" => ['title' => "Council of Deans — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "governance/council-scientific-research" => ['title' => "Council of Scientific Research — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/internal-control-unit" => ['title' => "Board of Trustees — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "governance/policy-agreements" => ['title' => "General Policy &amp; Agreements — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "governance/president-message" => ['title' => "Message from the President — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/presidents-assistant" => ['title' => "President's Assistant — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/about-deanship-grad" => ['title' => "About the Deanship — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/deanship-graduate-studies" => ['title' => "Deanship of Graduate Studies &amp; Scientific Research — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/deanship-graduate" => ['title' => "Graduate Studies — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/deanship-members" => ['title' => "Deanship Members — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/deanship-research" => ['title' => "Scientific Research — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/deanship-structure" => ['title' => "Deanship Structure — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/department-graduate-studies" => ['title' => "Department of Graduate Studies — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/department-scientific-research" => ['title' => "Department of Scientific Research — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/dispatching-department" => ['title' => "Dispatching Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/dispatching-forms" => ['title' => "Forms &amp; Rules — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/grad-forms" => ['title' => "Forms &amp; Reports (Graduate Studies) — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/grad-rules" => ['title' => "General Academic Rules (Graduate) — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/gs-dean-message" => ['title' => "Dean's Message — Graduate Studies — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/gs-members" => ['title' => "Deanship Members — Graduate Studies — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/gs-structure" => ['title' => "Deanship Structure — Graduate Studies — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/gs-thesis-guide" => ['title' => "Vision, Mission &amp; Objectives — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/gs-vision-mission" => ['title' => "Vision & Mission — Graduate Studies — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/journal" => ['title' => "Middle East Journal of Communication Studies — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/research-forms" => ['title' => "Forms &amp; Reports (Research) — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/scholarships" => ['title' => "Research Scholarships — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/staff-research-papers" => ['title' => "Academic Staff Research Papers — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs-erasmus" => ['title' => "Erasmus+ &amp; Partnerships — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs-projects" => ['title' => "Projects — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/deanship-international" => ['title' => "International Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/booklet" => ['title' => "MEU Booklet — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/events" => ['title' => "Events — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "media/magazine" => ['title' => "Eye on the Middle East Magazine — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "media/media-center" => ['title' => "Media Center — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "media/media-library" => ['title' => "Media Library — MEU Prototype 1.6", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/media-upload" => ['title' => "Media Upload — MEU Prototype 1.6", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/meu-newsletter" => ['title' => "MEU Newsletter — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/meu-pulse" => ['title' => "Middle East University — Learn. Belong. Lead. — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/news" => ['title' => "News Center — Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/newsletter" => ['title' => "MEU Newsletter — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "media/press" => ['title' => "MEU in the Press — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "media/year-books" => ['title' => "Year Books — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/activities" => ['title' => "Activities &amp; Clubs — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "student-affairs/alumni-association" => ['title' => "Alumni Network — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "student-affairs/careers" => ['title' => "Career Guidance & Alumni — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/deanship-students-affairs" => ['title' => "About the Deanship — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/deanship-students" => ['title' => "Deanship of Student Affairs — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "student-affairs/division-student-expatriates" => ['title' => "Division of Student Expatriates — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "student-affairs/division-student-services" => ['title' => "Division of Student Services — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "student-affairs/employers" => ['title' => "Employers & Recruiters — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/handbook" => ['title' => "Student's Handbook — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-dean-message" => ['title' => "Dean's Message — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-departments" => ['title' => "Departments — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-dept-activities" => ['title' => "Student Activities — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-dept-career" => ['title' => "Career Guidance & Alumni — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-dept-counseling" => ['title' => "Counseling & Psychological Services — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-dept-services" => ['title' => "Student Services & International — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-intolerance-policy" => ['title' => "Protection Against Intolerance & Discrimination Policy — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-members" => ['title' => "Deanship Members — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-structure" => ['title' => "Deanship Structure — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-vision-mission" => ['title' => "Vision & Mission — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sports" => ['title' => "Sports & Stadium — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/student-services" => ['title' => "Department of Student Services — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_Accounting_MA" => ['title' => "Study Plan — MA in Accounting | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_Arabic_BA" => ['title' => "Study Plan — BA in Arabic Language &amp; Literature | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_EduTech_BA" => ['title' => "Study Plan — BA in Educational Technology | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_English_BA" => ['title' => "Study Plan — BA in English Language &amp; Literature | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_MBA_MA" => ['title' => "Study Plan — MBA — Master of Business Administration | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_Media_MA" => ['title' => "Study Plan — MA in Media | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_PrivateLaw_MA" => ['title' => "Study Plan — MA in Private Law | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_PublicLaw_MA" => ['title' => "Study Plan — MA in Public Law | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_SportsMgmt_BA" => ['title' => "Study Plan — BA in Sports Management &amp; Coaching | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_Translation_BA" => ['title' => "Study Plan — BA in Applied Translation | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-about" => ['title' => "UK Degrees — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-alumni" => ['title' => "UK Alumni — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-apply" => ['title' => "Apply to MEU — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-bachelors" => ['title' => "Bachelor's (Bedfordshire) — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-contact" => ['title' => "UK Contact — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-degrees-meu" => ['title' => "UK Degrees MEU — UK degrees, earned in Amman", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-masters" => ['title' => "Master's Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-phd" => ['title' => "PhD Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
  ],
  "ar" => [
    "index" => ['title' => "Middle East University — Learn. Belong. Lead. — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => false],
    "sitemap" => ['title' => "Site Map — Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/accessibility" => ['title' => "الطلبة ذوو الاحتياجات الخاصة والترتيبات التيسيرية — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/accreditation" => ['title' => "الاعتماد — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/campus-library" => ['title' => "المكتبة — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/campus" => ['title' => "الحرم الجامعي — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/civic-engagement" => ['title' => "المشاركة المجتمعية — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/contact" => ['title' => "اتصل بنا — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/core-values" => ['title' => "القيم الجوهرية — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/facilities" => ['title' => "الحرم والمرافق — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/inquire" => ['title' => "اتصل بنا — جامعة الشرق الأوسط", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/library" => ['title' => "المكتبة — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/meu-general-policy" => ['title' => "السياسة العامة للجامعة — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/meu-in-numbers" => ['title' => "الجامعة بالأرقام — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/meu-in-words" => ['title' => "عن الجامعة — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/meu-map" => ['title' => "خريطة الجامعة — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/org-structure" => ['title' => "الهيكل التنظيمي — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/partnerships" => ['title' => "الشراكات والاتفاقيات الموقّعة — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/quality-assurance" => ['title' => "سياسة ضمان الجودة — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/strategic-plan" => ['title' => "الخطة الاستراتيجية والهيكل — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/university-objectives" => ['title' => "أهداف الجامعة — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/university-strategic-plan" => ['title' => "Strategic Plan 2019/2024 — Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/university-structure" => ['title' => "هيكل الجامعة — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/university-terminology" => ['title' => "المصطلحات الجامعية — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/vision-mission" => ['title' => "الرؤية والرسالة والأهداف — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "about/visit" => ['title' => "خطّط لزيارة — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "about/why-meu" => ['title' => "لماذا الجامعة؟ — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "academics/ects" => ['title' => "ECTS — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-allied-medical" => ['title' => "كلية العلوم الطبية المساندة — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-architecture" => ['title' => "كلية العمارة والتصميم — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-arts" => ['title' => "كلية الآداب والعلوم — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-business" => ['title' => "كلية الأعمال — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-it" => ['title' => "كلية تكنولوجيا المعلومات — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-law" => ['title' => "كلية الحقوق — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-media" => ['title' => "كلية الإعلام — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-nursing" => ['title' => "كلية التمريض — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/faculty-pharmacy" => ['title' => "كلية الصيدلة — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/master-programs" => ['title' => "Master&#x27;s Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/pg-majors" => ['title' => "Faculties & Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/prog-ai" => ['title' => "BSc Artificial Intelligence — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/prog-cis" => ['title' => "BSc Computer Information Systems — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/prog-cloud" => ['title' => "MSc Cloud Computing Services &amp; Security — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/prog-cs" => ['title' => "BSc Computer Science — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/prog-cyber" => ['title' => "BSc Cyber Security — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/programs" => ['title' => "Explore our Programs — MEU", 'bodyClass' => "about-page programs-page", 'css' => true, 'spacer' => true],
    "academics/technical-college" => ['title' => "Faculty of Technical College — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "academics/ug-majors" => ['title' => "Faculties & Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-engineering" => ['title' => "Engineering Services — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-financial" => ['title' => "Financial Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-health" => ['title' => "Health Care — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-hr" => ['title' => "Human Resources Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-it" => ['title' => "IT Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-legal" => ['title' => "Legal Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-media-pr" => ['title' => "Media & PR Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-presidency" => ['title' => "All Departments — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-procurement" => ['title' => "Procurement & Tendering — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admin-units/unit-warehouses" => ['title' => "Warehouses Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/admission" => ['title' => "Admission and Registration — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/certify-foreign" => ['title' => "Certifying Foreign Certificates — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/epayment" => ['title' => "Electronic Payment Steps — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/fees" => ['title' => "Fees — Tuition & Insurance | MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/hd-fees" => ['title' => "Tuition Fees (Higher Diploma) — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/pg-fees" => ['title' => "Fees & Insurance — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/pg-procedures" => ['title' => "Procedures — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/pg-requirements" => ['title' => "Admission Requirements — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/scholarships-aid" => ['title' => "Scholarships & Financial Aid — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/talent-scholarship" => ['title' => "Talent Scholarship | MEU Admission", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/transfer-students" => ['title' => "Transfer Students — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/ug-documents" => ['title' => "Documents Required — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/ug-fees" => ['title' => "Fees & Insurance — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/ug-procedures" => ['title' => "Procedures — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "admission/ug-requirements" => ['title' => "Admission Requirements — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-academic-development-achievements" => ['title' => "Achievements — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-academic-development-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-academic-development-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-academic-development-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-academic-development" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-accreditation-quality-achievements" => ['title' => "Achievements — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-accreditation-quality-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-accreditation-quality-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-accreditation-quality-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-accreditation-quality" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-consulting-training-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-consulting-training-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-consulting-training-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-consulting-training" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-heritage-revival-gallery" => ['title' => "Photo Gallery — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-heritage-revival-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-heritage-revival-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-heritage-revival-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-heritage-revival" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-hikmi-therapy" => ['title' => "Center for Therapeutic Therapy — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-house-of-art" => ['title' => "House of Art — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-innovation-entrepreneurship-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-innovation-entrepreneurship-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-innovation-entrepreneurship-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-innovation-entrepreneurship" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-media-training-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-media-training-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-media-training-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-media-training" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/center-recruitment" => ['title' => "Students Recruitment Center — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/centers-institutes" => ['title' => "Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "centers/training-enterprise" => ['title' => "Training & Enterprise — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/board-of-directors" => ['title' => "Board of Trustees — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "governance/board-of-trustees" => ['title' => "Board of Trustees — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/chairman-trustees" => ['title' => "Chairman of the Board of Trustees — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/control-audit" => ['title' => "Control & Internal Audit Unit — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/council-graduate-studies" => ['title' => "Council of Graduate Studies — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/council-of-deans" => ['title' => "Council of Deans — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "governance/council-scientific-research" => ['title' => "Council of Scientific Research — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/internal-control-unit" => ['title' => "Board of Trustees — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "governance/policy-agreements" => ['title' => "General Policy &amp; Agreements — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "governance/president-message" => ['title' => "Message from the President — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "governance/presidents-assistant" => ['title' => "President's Assistant — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/about-deanship-grad" => ['title' => "About the Deanship — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/deanship-graduate-studies" => ['title' => "Deanship of Graduate Studies &amp; Scientific Research — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/deanship-graduate" => ['title' => "Graduate Studies — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/deanship-members" => ['title' => "Deanship Members — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/deanship-research" => ['title' => "Scientific Research — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/deanship-structure" => ['title' => "Deanship Structure — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/department-graduate-studies" => ['title' => "Department of Graduate Studies — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/department-scientific-research" => ['title' => "Department of Scientific Research — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/dispatching-department" => ['title' => "Dispatching Department — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/dispatching-forms" => ['title' => "Forms &amp; Rules — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/grad-forms" => ['title' => "Forms &amp; Reports (Graduate Studies) — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/grad-rules" => ['title' => "General Academic Rules (Graduate) — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/gs-dean-message" => ['title' => "Dean's Message — Graduate Studies — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/gs-members" => ['title' => "Deanship Members — Graduate Studies — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/gs-structure" => ['title' => "Deanship Structure — Graduate Studies — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/gs-thesis-guide" => ['title' => "Vision, Mission &amp; Objectives — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/gs-vision-mission" => ['title' => "Vision & Mission — Graduate Studies — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "graduate-research/journal" => ['title' => "Middle East Journal of Communication Studies — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/research-forms" => ['title' => "Forms &amp; Reports (Research) — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/scholarships" => ['title' => "Research Scholarships — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "graduate-research/staff-research-papers" => ['title' => "Academic Staff Research Papers — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs-erasmus" => ['title' => "Erasmus+ &amp; Partnerships — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs-objectives" => ['title' => "Objectives — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs-projects" => ['title' => "Projects — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs-staff" => ['title' => "Staff — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs-vision" => ['title' => "Vision &amp; Mission — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/center-international-programs" => ['title' => "Overview &amp; Services — Centers &amp; Institutes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "international/deanship-international" => ['title' => "International Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/booklet" => ['title' => "MEU Booklet — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/events" => ['title' => "Events — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "media/magazine" => ['title' => "Eye on the Middle East Magazine — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "media/media-center" => ['title' => "Media Center — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "media/media-library" => ['title' => "Media Library — MEU Prototype 1.6", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/media-upload" => ['title' => "Media Upload — MEU Prototype 1.6", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/meu-newsletter" => ['title' => "MEU Newsletter — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/meu-pulse" => ['title' => "Middle East University — Learn. Belong. Lead. — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/news" => ['title' => "News Center — Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "media/newsletter" => ['title' => "MEU Newsletter — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "media/press" => ['title' => "MEU in the Press — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "media/year-books" => ['title' => "Year Books — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/activities" => ['title' => "Activities &amp; Clubs — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "student-affairs/alumni-association" => ['title' => "Alumni Network — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "student-affairs/careers" => ['title' => "Career Guidance & Alumni — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/deanship-students-affairs" => ['title' => "About the Deanship — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/deanship-students" => ['title' => "Deanship of Student Affairs — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "student-affairs/division-student-expatriates" => ['title' => "Division of Student Expatriates — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "student-affairs/division-student-services" => ['title' => "Division of Student Services — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "student-affairs/employers" => ['title' => "Employers & Recruiters — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/handbook" => ['title' => "Student's Handbook — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-dean-message" => ['title' => "Dean's Message — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-departments" => ['title' => "Departments — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-dept-activities" => ['title' => "Student Activities — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-dept-career" => ['title' => "Career Guidance & Alumni — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-dept-counseling" => ['title' => "Counseling & Psychological Services — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-dept-services" => ['title' => "Student Services & International — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-intolerance-policy" => ['title' => "Protection Against Intolerance & Discrimination Policy — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-members" => ['title' => "Deanship Members — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-structure" => ['title' => "Deanship Structure — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sa-vision-mission" => ['title' => "Vision & Mission — Deanship of Student Affairs — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/sports" => ['title' => "Sports & Stadium — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "student-affairs/student-services" => ['title' => "Department of Student Services — MEU", 'bodyClass' => "about-page", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_Accounting_MA" => ['title' => "Study Plan — MA in Accounting | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_Arabic_BA" => ['title' => "Study Plan — BA in Arabic Language &amp; Literature | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_EduTech_BA" => ['title' => "Study Plan — BA in Educational Technology | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_English_BA" => ['title' => "Study Plan — BA in English Language &amp; Literature | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_MBA_MA" => ['title' => "Study Plan — MBA — Master of Business Administration | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_Media_MA" => ['title' => "Study Plan — MA in Media | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_PrivateLaw_MA" => ['title' => "Study Plan — MA in Private Law | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_PublicLaw_MA" => ['title' => "Study Plan — MA in Public Law | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_SportsMgmt_BA" => ['title' => "Study Plan — BA in Sports Management &amp; Coaching | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "study-plans/MEU_StudyPlan_Translation_BA" => ['title' => "Study Plan — BA in Applied Translation | Middle East University", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-about" => ['title' => "UK Degrees — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-alumni" => ['title' => "UK Alumni — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-apply" => ['title' => "Apply to MEU — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-bachelors" => ['title' => "Bachelor's (Bedfordshire) — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-contact" => ['title' => "UK Contact — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-degrees-meu" => ['title' => "UK Degrees MEU — UK degrees, earned in Amman", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-masters" => ['title' => "Master's Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
    "uk/uk-phd" => ['title' => "PhD Programmes — MEU", 'bodyClass' => "", 'css' => true, 'spacer' => true],
  ],
];
